AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example AWS API endpoint

Resources:
  Example:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30000
      Events:
        Aggregations:
          Type: Api
          Properties:
            Path: /
            Method: any
